version: 2
jobs:
  build-linux:
    docker:
      - image: linuxbrew/brew
    environment:
      CIRCLE_REPOSITORY_URL: https://github.com/brewsci/homebrew-bio
      HOMEBREW_DEVELOPER: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_MAKE_JOBS: 4
    steps:
      - run: |
          cd /home/linuxbrew/.linuxbrew/Homebrew
          if [ -e .git/shallow ]; then git fetch --unshallow; fi
          git fetch origin --tags
          git reset --hard origin/master
          cd /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core
          git fetch origin --depth=1
          git reset --hard origin/master
      - checkout
      - run: |
          git remote set-url origin $CIRCLE_REPOSITORY_URL
          git fetch origin
          git config --global user.name LinuxbrewTestBot
          git config --global user.email testbot@linuxbrew.sh
          repo=$(brew --repo $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME)
          mkdir -p $repo
          cp -a ./ $repo/
      - run:
          no_output_timeout: 30m
          command: |
            mkdir /tmp/bottles
            cd /tmp/bottles
            umask 022
            PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"
            brew install patchelf
            brew tap linuxbrew/xorg
            brew test-bot --bintray-org=linuxbrew --root-url=https://linuxbrew.bintray.com/bottles-bio --git-name=LinuxbrewTestBot --git-email=testbot@linuxbrew.sh
      - persist_to_workspace:
          root: /tmp
          paths:
            - bottles/*
      - store_test_results:
          path: /tmp/bottles
  build-macos:
    macos:
      xcode: "10.2.0"
    environment:
      CIRCLE_REPOSITORY_URL: https://github.com/brewsci/homebrew-bio
      HOMEBREW_DEVELOPER: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - run: |
          brew --version
          brew remove $(brew list)
          rm -rf /usr/local/Homebrew/Library/Taps/
          brew update-reset
          brew --env
          brew config
      - checkout
      - run: |
          git remote set-url origin $CIRCLE_REPOSITORY_URL
          git fetch origin
          git config --global user.name LinuxbrewTestBot
          git config --global user.email testbot@linuxbrew.sh
          repo=$(brew --repo $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME)
          mkdir -p $repo
          cp -a ./ $repo/
      - run:
          no_output_timeout: 30m
          command: |
            mkdir /tmp/bottles
            cd /tmp/bottles
            brew test-bot --skip-setup --bintray-org=linuxbrew --root-url=https://linuxbrew.bintray.com/bottles-bio --git-name=LinuxbrewTestBot --git-email=testbot@linuxbrew.sh
      - persist_to_workspace:
          root: /tmp
          paths:
            - bottles/*
      - store_test_results:
          path: /tmp/bottles
  collect-bottles:
    docker:
      - image: linuxbrew/brew
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - store_artifacts:
          path: /tmp/workspace/bottles
          destination: bottles
workflows:
  version: 2
  test-bot:
    jobs:
      - build-linux
      - build-macos
      - collect-bottles:
          requires:
            - build-linux
            - build-macos
notify:
  webhooks:
    - url: https://p4142ivuwk.execute-api.us-west-2.amazonaws.com/prod/ci-upload
