version: 2
jobs:
  build:
    docker:
      - image: linuxbrew/linuxbrew
    environment:
      CIRCLE_REPOSITORY_URL: https://github.com/linuxbrew/homebrew-bioinformatics
      HOMEBREW_DEVELOPER: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_VERBOSE: 1
      HOMEBREW_VERBOSE_USING_DOTS: 1
    steps:
      - run: |
          cd /home/linuxbrew/.linuxbrew/Homebrew
          git fetch origin --unshallow --tags
          git reset --hard origin/master
      - checkout
      - run: git remote set-url origin $CIRCLE_REPOSITORY_URL
      - run: if [ -e .git/shallow ]; then echo git fetch --unshallow; fi
      - run: git fetch origin
      - run: git config --global user.name LinuxbrewTestBot
      - run: git config --global user.email testbot@linuxbrew.sh
      - run: chmod 0644 *.rb
      - run: mkdir -p /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew
      - run: cp -a . /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/$CIRCLE_PROJECT_REPONAME
      - run: mkdir /home/linuxbrew/bottles
      - run: >-
          cd /home/linuxbrew/bottles;
          umask 022;
          PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH";
          brew install patchelf
          && brew tap linuxbrew/xorg
          && brew test-bot
      - store_artifacts:
          path: /home/linuxbrew/bottles
      - store_test_results:
          path: /home/linuxbrew/bottles
notify:
  webhooks:
    - url: https://p4142ivuwk.execute-api.us-west-2.amazonaws.com/prod/ci-upload
